### ISSUE TITLE
Doesn't replace the default in memory session store

### ISSUE THREAD

**Issue by kdhindsa** [couchbaselabs/spring-session-data-couchbase#2]
I created a hello world project with azure ad for oauth and connfigured spring-session-data-couchbase as couchbase session store by following the tutorial.

It was able to store the sessions in the couchbase bucket however, when I deleted the sessions from couchbase admin console manually and refreshed the application, the sessions reappeared in couchbase.

It seems like the default in memory session store is still in the filter chain and somewhere along the line it is resetting the cookie and session from wherever it is storing, and then later on in the chain the couchbase filter is picking it up and thinking it is a new session.

**Comment by deniswsrosa** [comment]
Can you describe the use case? Because at first, I see no reason for deleting the session. It will be removed automatically after the TTL. This implementation also only stores/retrieves the data. The flow of when a session should be recreated is defined by Spring Session itself.

**Comment by kdhindsa** [comment]
Non-issue. Closing as per my previous comment.
